version: "3.8"
services:

  backend:
    build:  ./backend
    ports:
      - "3001:3001"
    container_name: backend_service
    restart: always

  frontend:
    build:  ./frontend
    ports:
      - "3000:3000"
    container_name: frontend_service
    restart: always